apiVersion: secrets.github.com/v1alpha1
kind: SecretRotation
metadata:
  labels:
    app.kubernetes.io/name: secret-rotator
    app.kubernetes.io/managed-by: kustomize
  name: secretrotation-sample
spec:
  vaultPath: "secret/data/myapp/database"
  targetSecret: "myapp-database-secret"
