apiVersion: secrets.github.com/v1alpha1
kind: SecretRotation
metadata:
  labels:
    app.kubernetes.io/name: secret-rotator
    app.kubernetes.io/managed-by: kustomize
  name: secretrotation-sample
spec:
  vaultPath: "secret/data/myapp"
  targetSecret: "myapp-secret"
  targetWorkloads:
    - kind: Deployment
      name: myapp-deployment
    - kind: StatefulSet
      name: myapp-statefulset
    # You can also specify workloads in different namespaces
    - kind: Deployment
      name: another-app
      namespace: other-namespace
  # Optional: customize the annotation prefix (defaults to "secrets.github.com/")
  annotationPrefix: "myapp.io/"
